Aodn notebook
rom-py/rompy-legacy pull request #14
Opened 2021-05-10 14:14 UTC by rfonsecadasilva

Add notebook with examples of using aodn catalog

Plots:
- lat/lon scatter coloured by Hs and time, SAR and altimetry (see utilfuncs.py)
- timeseries plot of Hs, SAR and altimetry

Other changes:
- lat/long crop filter (see filter.py) - (a)  note that although there is a spatial filter in the URL request, the retrieved dataset still includes data outside of the requested domain, thus a spatial filter is needed; and (b) note that as lat/lon are coordinates but not dimensions of the dataset, ds.sel(...) cannot be used, thus ds.where(...) had to be used and was added to crop_filter
- sort filter applied after concatenation of dataset - note that different chunks of dataset will have each sorted data, but concatenated may present unsorted data and thus needs to be sorted

2021-05-10 23:26 UTC, pbranson approved these changes
Thanks for this improvement

2021-05-10 23:28 UTC, pbranson approved these changes

2021-05-10 23:32 UTC, pbranson approved these changes
This is a useful change

2021-05-10 23:32 UTC, pbranson approved these changes

2021-05-10 23:49 UTC, pbranson requested changes
Thank @rfonsecadasilva, lets just move utilfuncs.py to rompy/plotting.py and import the scatter plot function from there.

2021-05-10 23:49 UTC, pbranson commented on notebooks/utilfuncs.py
> +def scatter(ds,color,minLon=None,minLat=None,maxLon=None,maxLat=None,fscale=10):
I wonder if we should start a plotting.py module within rompy and put this function there. Lets do that for now

2021-05-11 05:50 UTC, rfonsecadasilva commented on notebooks/utilfuncs.py
> +def scatter(ds,color,minLon=None,minLat=None,maxLon=None,maxLat=None,fscale=10):
This makes sense. By the way, I have to acknowledge that the scatter plotting function was inspired by BaseGrid/plot. Thanks, @pbranson .

2021-05-11 06:01 UTC, merged