Edit AODN altimetry catalog
rom-py/rompy-legacy pull request #9
Opened 2021-04-22 04:24 UTC by rfonsecadasilva

- add NetCDFAODNStackSource driver
- Add time filter to AODN catalog

2021-04-22 08:57 UTC, pbranson reviewed
This all looks good to me. If you can just tidy up the parameter descriptions in the catalog this looks gtg! Thanks!

2021-04-22 08:57 UTC, pbranson commented on rompy/catalogs/aodn.yaml
> +        description: Forecast date
This description should be start date - that was my slackness earlier. Can you fix these descriptions in the catalog entries.

2021-04-22 08:58 UTC, pbranson approved these changes

2021-04-22 09:01 UTC, pbranson commented
Actually is it possible for you to add a couple of tests too? Maybe a couple of pre-defined catalog entry requests where you know the length of the urlpath list and another where you know the length of the returned dataset.

2021-04-22 13:50 UTC, rfonsecadasilva commented on rompy/catalogs/aodn.yaml
> +        description: Forecast date
Sure, I fixed but I am not sure how to proceed. Should I close this PR, and submit a new one  (with new tests as per comment below)?

2021-04-22 15:34 UTC, rfonsecadasilva commented
> Actually is it possible for you to add a couple of tests too? Maybe a couple of pre-defined catalog entry requests where you know the length of the urlpath list and another where you know the length of the returned dataset.

Sure, I have now these two new tests in test_intake. (For now, they are in a new commit only on my fork.)

2021-04-23 02:01 UTC, pbranson commented
Thats good, thats how it works - any commits you add to your fork will come into this PR. That is why in general it is better to create a branch in your fork specific to the changes you want included in the PR

2021-04-23 02:59 UTC, pbranson requested changes
The tests are failing in your branch due to missing geopandas - can you add that to the requirements.txt

2021-04-23 03:10 UTC, pbranson commented
You will also need to pull updates from main. I have fixed the github actions so that the tests get run on the PR

2021-04-23 04:03 UTC, rfonsecadasilva commented
I added geopandas and merged upstream/main with your new changes.

2021-04-23 04:08 UTC, pbranson commented
The tests are still failing - thats because there is a separate requirements file that is used to setup the testing environment. Probably there is a better way to configure this so that there isnt duplication, but you also need to add to: https://github.com/rfonsecadasilva/rompy/blob/main/scripts/ci/environment-pip.yml 

To see your tests you can look here:
https://github.com/rfonsecadasilva/rompy/actions

2021-04-23 04:10 UTC, pbranson commented
And now the tests are running here so we should be able to monitor within this PR thread

2021-04-23 10:27 UTC, rfonsecadasilva commented
> The tests are still failing - thats because there is a separate requirements file that is used to setup the testing environment. Probably there is a better way to configure this so that there isnt duplication, but you also need to add to: https://github.com/rfonsecadasilva/rompy/blob/main/scripts/ci/environment-pip.yml
> 
> To see your tests you can look here:
> https://github.com/rfonsecadasilva/rompy/actions

Thanks, that's good to know. I've included geopandas and intake-geopandas and not the tests successfully passed on my fork.


> And now the tests are running here so we should be able to monitor within this PR thread

I couldn't find new tests running here in the PR (maybe you first have to approve them before it starts testing?)

2021-04-24 11:51 UTC, pbranson commented
Yeah that seemed to be because you hadnt made a commit to this repo before. I had to approve the CI run.

This all looks good - merging! 🎉

2021-04-24 11:51 UTC, merged